# Generated by Django 3.2.6 on 2021-10-08 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicks', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Advertiser',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='advertiser_management.basemodel')),
                ('name', models.CharField(max_length=50)),
            ],
            bases=('advertiser_management.basemodel',),
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='advertiser_management.basemodel')),
                ('title', models.CharField(max_length=50)),
                ('img_url', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
                ('advertiser_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertiser_management.advertiser')),
            ],
            bases=('advertiser_management.basemodel',),
        ),
    ]
