# Generated by Django 3.2.6 on 2021-10-11 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0002_auto_20211010_2146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='click',
            old_name='date',
            new_name='datetime',
        ),
        migrations.RenameField(
            model_name='view',
            old_name='date',
            new_name='datetime',
        ),
    ]
