# Generated by Django 2.2 on 2021-10-19 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celery_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hourreport',
            name='hour',
            field=models.IntegerField(default=13),
        ),
    ]
