# Generated by Django 2.2 on 2021-10-19 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celery_app', '0002_auto_20211019_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hourreport',
            name='hour',
            field=models.IntegerField(default=14),
        ),
    ]
