# Generated by Django 2.2 on 2021-10-19 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celery_app', '0003_auto_20211019_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hourreport',
            name='hour',
            field=models.IntegerField(default=15),
        ),
    ]
