# Generated by Django 2.2 on 2021-10-19 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celery_app', '0004_auto_20211019_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hourreport',
            name='hour',
            field=models.IntegerField(default=16),
        ),
    ]
