# Generated by Django 2.2 on 2021-10-19 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celery_app', '0005_auto_20211019_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hourreport',
            name='hour',
            field=models.IntegerField(default=17),
        ),
    ]
